### ISSUE TITLE
Dataflow List Error: "Invalid Server Response"

### ISSUE THREAD

**Issue by doublehelix4** [forcedotcom/Analytics-Cloud-Dataset-Utils#17] opened 2016-07-07 16:04 UTC
Dataflow List keeps failing with the error "List Dataflow failed, invalid server response". See screenshot. Other functions work fine, like Dataset list and File Upload. Same behavior occurs in Sandbox login.

![image](https://cloud.githubusercontent.com/assets/20341297/16659886/04a685dc-443a-11e6-86e9-029f33e4ac2a.png)

**Comment by datasetutil** [comment] 2016-07-07 16:06
This is known issue caused by the API changes in Summer'16 release. I have already checked in the fix. You can build from main or wait for the release

**Closed** 2016-07-07 16:09 UTC
